#!/bin/bash -l
#SBATCH --account=X
#SBATCH --job-name=X
#SBATCH --time=1:30:00
#SBATCH --partition=a100
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem-per-cpu=8G
#SBATCH --gres=gpu:2
#SBATCH --mail-type=all
#SBATCH --mail-user=X

ml purge
module load slurm/19.05.7
module load cuda/11.8.0
module load openmpi/4.1.4
ml
export CUDA_VISIBLE_DEVICES=0,1
GPUS_PER_NODE=2
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
nvcc -ccbin mpicxx -lmpi MultiGPU_MPI.cu -o MultiGPU_MPI && mpirun -np 2 ./MultiGPU_MPI > MultiGPU_MPI.log
nvcc -ccbin mpicxx -lmpi MultiGPU_MPI_streams.cu -o MultiGPU_MPI_streams && mpirun -np 2 ./MultiGPU_MPI_streams > MultiGPU_MPI_streams.log

